# Generated by Django 3.2.4 on 2021-07-24 05:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_auto_20210722_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_spicial',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('d', 'Darft'), ('p', 'Published'), ('i', 'Investigation'), ('b', 'Back')], max_length=1),
        ),
    ]
