# Generated by Django 3.2.4 on 2021-07-31 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210731_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='hist',
            field=models.ManyToManyField(blank=True, related_name='hits', to='blog.IPAddress'),
        ),
    ]
