# Generated by Django 3.2.4 on 2021-08-02 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_article_ratings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='ratings',
        ),
        migrations.DeleteModel(
            name='MyRating',
        ),
    ]
